var AddDados = function() {
    const total = 10;
    var data = [
        {Nome: "Natalie", Sobrenome: "Holden", Email: "hendrerit.Donec.porttitor@Vestibulumante.com"},
        {Nome: "Garrison", Sobrenome: "Stein", Email: "imperdiet@eutellusPhasellus.ca"},
        {Nome: "Walker", Sobrenome: "Cantu", Email: "aliquam@Nunclaoreetlectus.net"},
        {Nome: "Brittany", Sobrenome: "Perry", Email: "lacus.vestibulum@estmollisnon.edu"},
        {Nome: "Nolan", Sobrenome: "Fry", Email: "imperdiet.dictum.magna@commodo.com"},
        {Nome: "Lydia", Sobrenome: "Colon", Email: "et.ultrices@atpretiumaliquet.com"},
        {Nome: "Lance", Sobrenome: "Sweeney", Email: "ut.pellentesque.eget@orciconsectetuer.co.uk"},
        {Nome: "Martha", Sobrenome: "Long", Email: "vel.lectus@auctorveliteget.ca"},
        {Nome: "Holly", Sobrenome: "Donaldson", Email: "mauris@Nullam.org"},
        {Nome: "Ian", Sobrenome: "Baker", Email: "Nunc@Fuscefeugiat.net"},
        {Nome: "Wyoming", Sobrenome: "Rasmussen", Email: "facilisis.Suspendisse.commodo@arcuimperdiet.org"},
        {Nome: "Linda", Sobrenome: "Bird", Email: "feugiat@adipiscing.ca"},
        {Nome: "Sylvia", Sobrenome: "Stephens", Email: "pharetra.felis.eget@elitpretium.edu"},
        {Nome: "Nathan", Sobrenome: "Duke", Email: "neque.In@leoinlobortis.ca"},
        {Nome: "Lance", Sobrenome: "Harris", Email: "ac.urna@laciniaatiaculis.co.uk"},
        {Nome: "Francis", Sobrenome: "Baker", Email: "quam.dignissim.pharetra@odiosagittissemper.com"},
        {Nome: "Bradley", Sobrenome: "Santiago", Email: "aliquam@Duismienim.com"},
        {Nome: "Amethyst", Sobrenome: "Wooten", Email: "metus@parturientmontes.org"},
        {Nome: "Dorothy", Sobrenome: "Watson", Email: "nibh.vulputate@elitNullafacilisi.edu"},
        {Nome: "Lavinia", Sobrenome: "Roberts", Email: "Nulla@feugiat.co.uk"},
        {Nome: "Kelly", Sobrenome: "Ortega", Email: "amet@nibhvulputatemauris.com"},
        {Nome: "Daryl", Sobrenome: "Blanchard", Email: "inceptos.hymenaeos@penatibusetmagnis.com"},
        {Nome: "Lucian", Sobrenome: "Burns", Email: "Sed@placeratvelitQuisque.edu"},
        {Nome: "Kibo", Sobrenome: "Spencer", Email: "suscipit@luctus.co.uk"},
        {Nome: "Lyle", Sobrenome: "Delaney", Email: "Cum.sociis.natoque@euarcu.ca"},
        {Nome: "Brandon", Sobrenome: "Tyson", Email: "pede.et@tinciduntduiaugue.org"},
        {Nome: "Britanney", Sobrenome: "Matthews", Email: "Suspendisse.sed@dapibusquam.org"},
        {Nome: "Adara", Sobrenome: "Dale", Email: "imperdiet.nec@eutemporerat.org"},
        {Nome: "Nayda", Sobrenome: "Baxter", Email: "vestibulum@ornarefacilisiseget.co.uk"},
        {Nome: "Gisela", Sobrenome: "Steele", Email: "lectus.quis@loremsitamet.edu"},
        {Nome: "Clinton", Sobrenome: "Jenkins", Email: "eu.tempor.erat@etmagnisdis.org"},
        {Nome: "Ignacia", Sobrenome: "Mcfadden", Email: "vel.convallis@orciUtsagittis.net"},
        {Nome: "Drew", Sobrenome: "Briggs", Email: "dis@luctusvulputate.ca"},
        {Nome: "Shea", Sobrenome: "Nieves", Email: "quis.turpis.vitae@ipsumdolorsit.org"},
        {Nome: "Neve", Sobrenome: "Trevino", Email: "eu@estconguea.edu"},
        {Nome: "Karina", Sobrenome: "Moore", Email: "vitae@elementumdui.ca"},
        {Nome: "Sandra", Sobrenome: "Vincent", Email: "mi@quis.org"},
        {Nome: "Ruby", Sobrenome: "Fernandez", Email: "Aenean.eget.magna@velit.edu"},
        {Nome: "Nissim", Sobrenome: "Pollard", Email: "augue.eu@volutpat.co.uk"},
        {Nome: "Isabelle", Sobrenome: "Massey", Email: "amet.consectetuer@cubiliaCuraePhasellus.edu"},
        {Nome: "Julian", Sobrenome: "Williams", Email: "pharetra.nibh@placerat.org"},
        {Nome: "Zena", Sobrenome: "Moon", Email: "montes@velitdui.ca"},
        {Nome: "Warren", Sobrenome: "Bates", Email: "sollicitudin.commodo.ipsum@urna.co.uk"},
        {Nome: "Regan", Sobrenome: "Hendrix", Email: "interdum.libero@sodalespurus.net"},
        {Nome: "Blaze", Sobrenome: "Conner", Email: "sem@iaculis.ca"},
        {Nome: "Reuben", Sobrenome: "Le", Email: "ante.dictum.cursus@et.edu"},
        {Nome: "Vladimir", Sobrenome: "Alford", Email: "Nulla@laoreetlectusquis.edu"},
        {Nome: "Adrienne", Sobrenome: "Tate", Email: "erat.vitae.risus@sociis.net"},
        {Nome: "August", Sobrenome: "Keith", Email: "tortor.Integer@Integervulputate.org"},
        {Nome: "Roanna", Sobrenome: "Snow", Email: "aliquet.libero.Integer@Namac.net"},
        {Nome: "Suki", Sobrenome: "Gillespie", Email: "dolor@ametmetus.org"},
        {Nome: "Leila", Sobrenome: "Todd", Email: "Morbi.vehicula@Duismienim.ca"},
        {Nome: "Galvin", Sobrenome: "Kane", Email: "eros.Nam.consequat@risus.com"},
        {Nome: "Aline", Sobrenome: "Lloyd", Email: "elit.dictum.eu@feugiatSed.net"},
        {Nome: "Jonas", Sobrenome: "Quinn", Email: "sit.amet.risus@Craseutellus.ca"},
        {Nome: "Raya", Sobrenome: "Stanley", Email: "vel.lectus@ipsumcursus.ca"},
        {Nome: "Xanthus", Sobrenome: "Ratliff", Email: "Phasellus@ridiculusmus.ca"},
        {Nome: "Tanya", Sobrenome: "Nieves", Email: "Donec@interdumligula.com"},
        {Nome: "Alexis", Sobrenome: "Brooks", Email: "eu.arcu@posuereenimnisl.ca"},
        {Nome: "Declan", Sobrenome: "Crane", Email: "posuere.cubilia.Curae@blandit.net"},
        {Nome: "Jemima", Sobrenome: "Barlow", Email: "nibh.vulputate@Quisque.edu"},
        {Nome: "Vladimir", Sobrenome: "Vazquez", Email: "augue.eu@egetmetus.edu"},
        {Nome: "Noble", Sobrenome: "Bernard", Email: "ultricies.ornare.elit@Duis.ca"},
        {Nome: "Trevor", Sobrenome: "Marshall", Email: "at.nisi@elitNulla.edu"},
        {Nome: "Dakota", Sobrenome: "Duncan", Email: "vitae.risus.Duis@QuisquevariusNam.ca"},
        {Nome: "Debra", Sobrenome: "England", Email: "Etiam@auctorMaurisvel.net"},
        {Nome: "Kai", Sobrenome: "Nunez", Email: "dui@nisinibh.co.uk"},
        {Nome: "Kai", Sobrenome: "Sloan", Email: "sit@Maurismolestie.edu"},
        {Nome: "Signe", Sobrenome: "Ross", Email: "arcu.Sed.et@facilisiSed.ca"},
        {Nome: "Dorothy", Sobrenome: "Dean", Email: "Duis.cursus@velit.co.uk"},
        {Nome: "Marshall", Sobrenome: "Bullock", Email: "aliquet.lobortis@acfermentum.ca"},
        {Nome: "Fulton", Sobrenome: "Carson", Email: "ligula.Nullam@Integerin.com"},
        {Nome: "Ora", Sobrenome: "Lowe", Email: "aliquam@egetvolutpat.com"},
        {Nome: "Amity", Sobrenome: "Boyer", Email: "risus.a@eutellus.co.uk"},
        {Nome: "Lavinia", Sobrenome: "Pierce", Email: "et.pede@temporaugue.com"},
        {Nome: "Guy", Sobrenome: "Duncan", Email: "Vivamus@eleifendegestas.org"},
        {Nome: "Ingridy", Sobrenome: "Hall", Email: "cursus@erosturpis.ca"},
    ];    
    //var indice = parseInt(Math.random() * (101 - 0) + 0);
    var indice = parseInt(Math.random() * (75 - 0) + 0);
    document.getElementById("nome").value = data[indice].Nome;
    document.getElementById("sobrenome").value = data[indice].Sobrenome;
    document.getElementById("email").value = data[indice].Email;
    document.getElementById("credito").value = (Math.random() * (250.30 - 14.50) + 14.50).toFixed(2);
}
